### ISSUE TITLE
Blender crash on skeleton export

### ISSUE THREAD

**Issue by GrizzlyOne95** [Lucius64/kenshi_io_blender#1]
### Add-on version

3.6

### Blender version

3.6

### Steps to reproduce the bug

I load a mesh with skeleton attached. I'm trying to simply delete a bone out of the armature and then re-export the mesh and skeleton with that bone removed. I've tried deleting the associated vertex groups and mesh, or just the bone, and it instantly crashes blender either way. 
![image](https://github.com/Lucius64/kenshi_io_blender/assets/143971298/b8f57d68-fae0-45f3-ba77-8d58b551acad)
I've tried various export/import options and cleared all other addons just in case but that hasn't helped. 

### Expected behavior

I would expect the mesh/skeleton to export with no issues, or at least an error if not. I can export the mesh/skeleton with no bone changes fine. 

### Actual behavior

Blender hard crashes with no error and disables the addon.

**Comment by GrizzlyOne95** [comment]
Here is my BLEND. Bone I'm trying to remove is named HLGT0_ffffff
[avtanknl.zip](https://github.com/Lucius64/kenshi_io_blender/files/13795656/avtanknl.zip)

**Comment by Lucius64** [comment]
Thanks for the report.
I checked the reproduction of the issue.
I will release a patch soon.

**Comment by GrizzlyOne95** [comment]
Thank you!
